# NOTE: update this with your service name
service: serverless-nodejs-starter

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ca-central-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  pdf-base64:
    handler: src/index.handler
    events:
      - http:
          path: pdf-base64
          method: get
          cors: true

custom:
  bundle: 
    copyFiles:                   # Copy any additional files to the generated package
    - from: 'src/*'              # Where the files are currently
      to: './' 